name: ssd-causal
channels:
  - conda-forge
  - bioconda
  - defaults
  - r

dependencies:
  # Python dependencies
  - python=3.12
  - pandas=2.2.3
  - numpy=1.26.0
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - xgboost=2.0.0
  - lightgbm=4.1.0
  - pytest=7.4.0
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - papermill=2.4.0
  - pyyaml=6.0.1
  - openpyxl=3.1.2
  - pyarrow=13.0.0
  - tabulate=0.9.0
  - tqdm=4.66.0
  
  # R dependencies  
  - r-base=4.3.0
  - r-tidyverse=2.0.0
  - r-MatchIt=4.5.0
  - r-survey=4.2.0
  - r-grf=2.3.0
  - r-tmle=2.0.0
  - r-SuperLearner=2.0.28
  - r-glmnet=4.1.0
  - r-ranger=0.15.0
  - r-xgboost=1.7.0
  - r-mice=3.16.0
  - r-sandwich=3.0.0
  - r-lmtest=0.9.0
  - r-car=3.1.0
  - r-boot=1.3.0
  
  # Mixed language support
  - rpy2=3.5.0
  
  # Additional pip packages
  - pip:
    - miceforest==5.6.3
    - causalml==0.14.0
    - EconML==0.14.0
    - graphviz==0.20.0
    - python-dotenv==1.0.0
    - click==8.1.0
    - rich==13.5.0
    
# Environment metadata
# Created: 2025-06-17
# Purpose: SSD Causal Inference Pipeline - Combined Python/R environment
# Maintainer: Ryhan Suny <sunnyrayhan2@gmail.com>