name: ssd-causal
channels:
  - conda-forge
  - bioconda
  - defaults
  - r

dependencies:
  # Python dependencies - using 3.11 for better R compatibility
  - python=3.11
  - pandas>=2.0
  - numpy>=1.24
  - scikit-learn>=1.3
  - statsmodels>=0.14
  - matplotlib>=3.7
  - seaborn>=0.12
  - lightgbm>=3.3
  - pytest>=7.0
  - jupyter>=1.0
  - ipykernel>=6.0
  - papermill>=2.4
  - pyyaml>=6.0
  - openpyxl>=3.1
  - pyarrow>=12.0
  - tabulate>=0.9
  - tqdm>=4.65
  
  # R dependencies - using flexible versions
  - r-base=4.3.*
  - r-tidyverse
  - r-MatchIt
  - r-survey
  - r-grf
  - r-tmle
  - r-SuperLearner
  - r-glmnet
  - r-ranger
  - r-xgboost
  - r-mice
  - r-sandwich
  - r-lmtest
  - r-car
  - r-boot
  - r-survival
  - r-cmprsk
  
  # Mixed language support
  - rpy2>=3.4
  
  # Additional pip packages
  - pip
  - pip:
    - miceforest>=5.6
    - causalml>=0.14
    - EconML>=0.14
    - dowhy>=0.11
    - graphviz>=0.20
    - python-dotenv>=1.0
    - click>=8.1
    - rich>=13.0
    - xgboost>=1.7
    
# Environment metadata
# Created: 2025-06-17
# Purpose: SSD Causal Inference Pipeline - Combined Python/R environment
# Maintainer: Ryhan Suny <sunnyrayhan2@gmail.com>
# Fixed: Compatibility issues resolved for Docker deployment